### ISSUE TITLE
iOS auto-off

### ISSUE THREAD

**Issue by blowonthepi** [songyiYu/all_sensors#3]
By just adding the plugin my apps screen turns off when I have close proximity.

**Comment by th8m0z** [comment]
I'm having the same issue. Any workarounds?

**Comment by blowonthepi** [comment]
I haven’t found a solution yet sorry.

**Comment by th8m0z** [comment]
I fixed the problem by cancelling the stream subscription everywhere in my app. Apparently I was subscribing on two different occasions and only canceled one of them. Now everything works as expected and the screen doesn't automatically turn off.

**Comment by songyiYu** [comment]
I think you should find somewhere missing unsubscribe stream. I'll close this issue

**Comment by mazen930** [comment]
@blowonthepi  @th8m0z  i suffer from this problem in andorid , i use the example and it failed , i try to destroy but it also fail , so any idea how to solve this , 
@songyiYu  in case you have a solution , i even tried the example alone and it have same issue , seems like cancel(), doesn't do anything

**Comment by mazen930** [comment]
After further testing , it happens on android only for me
